---

jobs:
  include:
    - stage: Build

      language: minimal
      services:
        - docker
      script: docker build --build-arg CODECOV_TOKEN -t "${DOCKER_USER}/$(make name):$(make version)" .

    - stage: Publish

      language: minimal
      script:
        - curl -q -sSL --max-time 10 -X POST https://goreportcard.com/checks?repo=github.com/${TRAVIS_REPO_SLUG}

stages:
  - Build
  - name: Publish
    if: branch = master && type = push

notifications:
  email: false
