[[constraint]]
  branch = "master"
  name = "github.com/ViBiOh/auth"

[[constraint]]
  branch = "master"
  name = "github.com/ViBiOh/httputils"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true
