---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hue-config
  namespace: default
  labels:
    app.kubernetes.io/name: hue
    app.kubernetes.io/instance: hue
    app.kubernetes.io/managed-by: kubectl
data:
  config.json: |
    {
      "motion_sensors": {
        "crons": []
      }
    }
