---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hue
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hue
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
