---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hue-auth
  namespace: default
spec:
  encryptedData:
    users: AgBHYa358nher8z/7toY3X80r3Ec1u7e+46TAHZSp9WJUwLgi+LurLZzq4f5erJO2DTY4WVApQJUA9uEyl3i0yxS85k9q56p22pFvQF5hgrf24Q5F3OCU8ams1RBIhyTwuG3sqin05VouMJUyXt93oRyrFG8efmXY3Rru5X23IH13uaJ9g3MY9YEJuHUH/DWQF6myc4MaiaonsmN0U+XhJGlA1xyo3IjnmItVK5xqxsEdROgOGEfEZzgsNlEmsYi4klpZbULiMwH2txOlztE0rrrjH4YzXSXTPzOJcYdFcf4wYd0/E735bZOmYT5/6xN40c1CjmQx+/WPVMWhqHlFrtHgUSXtihgiXXaHPhdrSSVogfmBqJvU7y5FFs7UlDOrRdc/jsZ0Hs5nq0MDe2WDwpbNbqgNXnJdBKtn1jD2Yc3xlLTFAqlugfcn4T2kaLJLimw8pQVvzfu/dmsV9fF9HEJBs1OtyHQHgEZfJ+HCDCrPEr4+l1HfCpsx66GjgERU2Fh+jzIK0vT203zz6bpUTzIIhKhYba2Km3322wbuamRL53/n44Kga3OtFrys7tJc8JqzD3RzKsFpyYfyrq55UT1d18kPF1uQrjXyXJVeBXmY/7kW8aZPGErrWaC1kq1136FZMhmiCZZagd4Hw98/YvoqU3HedNINj3IttfUkBrX1X2CI+OzvMPVe5kvQwJAkmPrc0G0LQ5Sn8GQzYaZ4OBFphVbNJfchD1h7N/lNUICa7M1ZrvKjFU5mHnOBWa1zS5T+/ncSRMp90YBWCcq2rb70L6g
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: hue-auth
  namespace: default
  labels:
    app.kubernetes.io/name: hue
    app.kubernetes.io/instance: hue
    app.kubernetes.io/managed-by: kubectl
spec:
  basicAuth:
    secret: hue-auth
    removeHeader: true
---
apiVersion: v1
kind: Service
metadata:
  name: hue
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: hue
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.1.120
    ports:
      - port: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hue
  namespace: default
  labels:
    app.kubernetes.io/instance: hue
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/name: hue
spec:
  secretName: hue-tls
  dnsNames:
    - hue.vibioh.fr
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
    group: cert-manager.io
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  labels:
    app.kubernetes.io/instance: hue
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/name: hue
  name: hue-http
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`hue.vibioh.fr`)
      middlewares:
        - name: ratelimit@file
        - name: compress@file
        - name: redirect@file
      services:
        - name: hue
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  labels:
    app.kubernetes.io/instance: hue
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/name: hue
  name: hue-https
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`hue.vibioh.fr`)
      middlewares:
        - name: ratelimit@file
        - name: compress@file
        - name: hue-auth
          namespace: default
      services:
        - name: hue
          port: 80
  tls:
    secretName: hue-tls
