---
apiVersion: v1
kind: Service
metadata:
  name: hue
  labels:
    app.kubernetes.io/name: hue
    app.kubernetes.io/instance: hue
    app.kubernetes.io/managed-by: kubectl
spec:
  selector:
    name: hue
  ports:
    - name: http
      port: 80
      targetPort: http
