apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hue-user
  namespace: default
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hue-user
spec:
  encryptedData:
    username: AgA8nQ9DQlcdRjMsk8pZQBmzpnU48IarR7T0/Gb3vbFoXDfWLEUYp1f/MyPdii1YKX25001bd8+XuWjycmjJwM6ERU1nUp2iLXhgwRB5Jdo88MUrUxh70KB6brtNFDJFy+dhEciZtf4nl6aEwTgGzLQ+4WFX1XnQuCWy0QFUjbIkSSIr1r5Mabh3LenLyOPp0H2uDBmFw9eDwwAhVIz+f77W9Xyl/Scj6rfJS4dGaM0CRv8XHSeqs7ucvVhAk3h1GQnxZZUwDABxTBeK0GsxylODjFRcwqeuFJDNAgpnoTkBmLJiiPwkj3pCuzyDRMYlr4PGdggJbbyienVCH1yC0VTYbd8J/cg1gahxjyZy53NVaKwYzDi3rMQuNNqn1xAD8IlWrSJONkcYJOF3chps40HN5oMAoRC/jTt7pT60mMfuut53/8Pv+kDTNrGToYF1jcYd/0jZW5/aKPwIuDkNRTpFS/clGZNilwumCsLuQ5Dy4VJSDfqjudKTmkJf3a/osP9DSE5imt3+xLfN9PsKn077LleAYHfOT2yyllzF7iiP05++EdUGgXg+niKuL8nsN7TwvtyZKcnJk8ooWeOLBYP7TTGrswRoqnrYawNicb8buRtUNhtLbhiKnmtFibReHJUMUhdyddAOXFGnUIZZ7v8RePnpMhu1PPaNZEOvd8wOS6foAL69icrDULg+KcAF+jEIjr/QjsQ=
    password: AgARv2WZUU5m2mwRx/TvKra734A1ym0eDDxfwYKnJA3//QhtOO4rRvk94IyZDnAj0QtRgFZ3Hf2+JKnJwyJKjReR8yVwnhAdlVKQ4RH3AnWbc7J1f3+M/LTuVkaPe3IxSQtFDdxEVs5dp3GB09JPIryN2X5bFIXJz0ONPZOSFzye1TxAqAyQdcxPdYrdKlMZ8H/E0fRuOQoC/wJJs33B0PSmxY9ELqpvnsPNzNKnkXgPBimptrQnjHpYe5YHUicMzgZ1s4+8GQOfBeZCrES0OXyZ1+hBr2bxTebU61QMMlyDjCmdHWTnI8Osx49he1vhoF3VHze8JkTR1+v2WdvFYSOO8UJUYOLeyKUtH+NeSXfOlGWL3vuxUHGLYULBIAZcJ4VVXxFaH4d2jpo44O3K8xzbp9NuBcaG9IHksP3ec4UOkKWNKRQs71lDPdwerqnz1+EINAfsrIaugFV99Dc2z8rsni8aEVINFPQx+K/3juUzD0uFP3aGTu+O2h8JFsf7b1r9wyUO2TeBFP8KyAg2z+TLYPeLqSgdXNOenicrmnROYM8EPv3DS9rMjpjLLndUpYfS0CzFKtVfTYzt3oLCZ3ULTyttXgawIkRdUaqdu8ZZBdscos/8ijcPFreQRJoN2SR5I9S7Nh2PdAeWikUmDts3hNb6sjhrYtVW/RYS6w97CCj7bbPXTZ7RuHS5DpWKPBxlEgYBQc+wqmF3G0jvU/SIVnvqnXuBHSXd
  template:
    type: kubernetes.io/basic-auth
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: hue-auth
  namespace: default
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hue-auth
spec:
  basicAuth:
    secret: hue-user
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hue
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.1.7"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: hue
    image:
      name: vibioh/hue
      tag: "202503302235" # {"$imagepolicy": "default:flux-hue-api:tag"}
    labels:
      tags.datadoghq.com/env: "production"
      tags.datadoghq.com/service: "hue"
      tags.datadoghq.com/version: "202503302235" # {"$imagepolicy": "default:flux-hue-api:tag"}
    config:
      HUE_BRIDGE_IP: "10.100.3.10"
      HUE_CONFIG: /opt/config.json
      HUE_LOGGER_JSON: "true"
      HUE_PPROF_AGENT: http://datadog.observability:8126
      HUE_PUBLIC_URL: "10.100.4.20"
      HUE_TELEMETRY_RATE: "0.01"
      HUE_TELEMETRY_URL: datadog.observability:4317
      HUE_V2_BRIDGE_IP: "10.100.3.10"
      OTEL_RESOURCE_ATTRIBUTES: env=production,git.repository_url=github.com/ViBiOh/hue
    volumes:
      - name: config
        configMap:
          name: hue-config
    volumeMounts:
      - name: config
        mountPath: /opt
    env:
      - name: GOMAXPROCS
        valueFrom:
          resourceFieldRef:
            resource: limits.cpu
      - name: GOMEMLIMIT
        valueFrom:
          resourceFieldRef:
            resource: limits.memory
      - name: VERSION
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['tags.datadoghq.com/version']
      - name: OTEL_SERVICE_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['tags.datadoghq.com/service']
    secrets:
      HUE_USERNAME: AgBzRhoc+24UDQkvM7Pl6ByDzKf/uFwRI9DHzQ7/kb6fBRWKonf4u0ruJTq1WZCLSEty0p4V4OnJm0YRtcQj3LjAey85HZOHeKaG1fLqlVYT6x1JqupgjxX320CCqzk1wjcbcpLxRxWvcR9hyc+lccVuVk6miiFaHgX/lNrmt2FOvPGfO5vrBSosGUsTsCGVkV7Bt6Ak60zUf/OoFUOKdj94akaPLKyC1UPP+uI/+gtAcZommB3lP35GGXEtjR6bn4YAwEMxib61GWg0KFy7rDLu3RMYHRvVsviTDhdnZ3sdj1goQoTRBtOQKfIe3lWMk3sAX1/ARXZkAiuL0bjrQt1vVxojLAuwBwnt1F4vo8Gmw0hOu4b9YFoa6Cedo6gxJLHZKdtgX8Cw66uRFjs3JW8MPTQ+xbx5GdmpFuUbgU4mWaeVTew0QjkFlne+RLAOFMA26Is/NxFD5sVGxCat91VNIC4O3Th2udhYcC/XEzbLkj2MOg5COwIiejkYwxVaf0UmjFCkFm9Tn+hT245q9+wcyYX3o1BXJVCuSu7KaTqv73Y0WGiMoNiliPg9QetjP5Ez1fXGRC4Vj/9zVDaGD7zaJuMuYtV45HGQBvn1+UVeLEyIwNdaDlDw0Pj3g5mZz5x9LamqFqA8v+VVpKDbTX24gOr0xWoIbGsJgnitTUcxluGRp2UQ8C/RgQtdD6kXLPw/db1EduL4pNshn92ySaTZyl1mBjnMh2uesJyF8sh7k+3FVP/zHTa5
      HUE_V2_USERNAME: AgBzRhoc+24UDQkvM7Pl6ByDzKf/uFwRI9DHzQ7/kb6fBRWKonf4u0ruJTq1WZCLSEty0p4V4OnJm0YRtcQj3LjAey85HZOHeKaG1fLqlVYT6x1JqupgjxX320CCqzk1wjcbcpLxRxWvcR9hyc+lccVuVk6miiFaHgX/lNrmt2FOvPGfO5vrBSosGUsTsCGVkV7Bt6Ak60zUf/OoFUOKdj94akaPLKyC1UPP+uI/+gtAcZommB3lP35GGXEtjR6bn4YAwEMxib61GWg0KFy7rDLu3RMYHRvVsviTDhdnZ3sdj1goQoTRBtOQKfIe3lWMk3sAX1/ARXZkAiuL0bjrQt1vVxojLAuwBwnt1F4vo8Gmw0hOu4b9YFoa6Cedo6gxJLHZKdtgX8Cw66uRFjs3JW8MPTQ+xbx5GdmpFuUbgU4mWaeVTew0QjkFlne+RLAOFMA26Is/NxFD5sVGxCat91VNIC4O3Th2udhYcC/XEzbLkj2MOg5COwIiejkYwxVaf0UmjFCkFm9Tn+hT245q9+wcyYX3o1BXJVCuSu7KaTqv73Y0WGiMoNiliPg9QetjP5Ez1fXGRC4Vj/9zVDaGD7zaJuMuYtV45HGQBvn1+UVeLEyIwNdaDlDw0Pj3g5mZz5x9LamqFqA8v+VVpKDbTX24gOr0xWoIbGsJgnitTUcxluGRp2UQ8C/RgQtdD6kXLPw/db1EduL4pNshn92ySaTZyl1mBjnMh2uesJyF8sh7k+3FVP/zHTa5
    autoscaling:
      enabled: false
    ingress:
      enabled: true
      compress: true
      tls:
        enabled: true
      hosts:
        - hue.vibioh.fr
      https_middlewares:
        - hue-auth
