apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: hue
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.1.2"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: hue
    image:
      name: vibioh/hue
      tag: "202402092001" # {"$imagepolicy": "default:flux-hue-api:tag"}
    labels:
      tags.datadoghq.com/env: "production"
      tags.datadoghq.com/service: "hue"
      tags.datadoghq.com/version: "202402092001" # {"$imagepolicy": "default:flux-hue-api:tag"}
    config:
      HUE_CONFIG: /opt/config.json
      HUE_LOGGER_JSON: "true"
      HUE_TELEMETRY_RATE: "0.01"
      HUE_TELEMETRY_URL: datadog.observability:4317
      OTEL_RESOURCE_ATTRIBUTES: env=production,git.repository_url=github.com/ViBiOh/hue
    volumes:
      - name: config
        configMap:
          name: hue-config
    volumeMounts:
      - name: config
        mountPath: /opt
    env:
      - name: GOMAXPROCS
        valueFrom:
          resourceFieldRef:
            resource: limits.cpu
      - name: GOMEMLIMIT
        valueFrom:
          resourceFieldRef:
            resource: limits.memory
      - name: VERSION
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['tags.datadoghq.com/version']
      - name: OTEL_SERVICE_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['tags.datadoghq.com/service']
    secrets:
      HUE_PUBLIC_URL: AgAnV14Enh3p66yStVwzPzZ3UdqEcdSMP+9+f/6O54Xr3baKSPD8InGdGlDe9BsKulhWI1HuZxeXimSLJCiWr++Z5+6Ccn3JMdv0fiyGysHYAbFSxpVs5VZYgUk5Yr4mwb23N2wSwhha3InmgBjgqt5qci5WZYGWJAw1WilCST6pHdCmTzogrbtsrHhFfT3Qnyz2L1N9NlQcgGuWbznXY/oToo9UXe/ABDE3gpipZSDFA1CuKzpuyK7uANTbsv6w6SxB2pTMF4agSpHedKcGOWNnzHMTtMNAOUU8Mj8Ial6b1ktR6Dtq8Nb7jC9dt11wNZ7htw65LKUAPpJRhKiu4fTGkH6kuQ2mnmcW02gN6N5FEAiDNP0nNN+70/XJpYR01HOD/uvHATJIHcxg5TnPvbhQNRlnvUcuu6F2p2SQf8mJ712FrfraGSSqVyNTw2sIxncaG3+Z+YoRdwplrzoxM948wGnPHmPjOO47eplYPYeLW5L13OG+RTRbtTiB4wnxn7Upoid8phXtCmLhaQRci2GhrbDdrYnTZCqajl9vm0Ap/y/CSqAP9zORd7wp/Tuwb/yoT6souuPapXaMt+mh8yXP/7eHMbpxIgQutOjShzlzxBtJQb+Civi06ZQmtInN+Bs2iptxePAU4zIU6XBb9Vm4Mn/KE2aHlOJf4QPhmVc6Y1arDFmkYiIa25v0mAmLAQIzEbiPKmJSzCQr4UR04g9xbPlong==
      HUE_BRIDGE_IP: AgBz58wuPR+a9DZ4VQ0v5HKwjbmkfNXwDbZnwONPZ6i0elWf3EfIVh9WaMZm2LeyvLOjpPquk6UGsmnS/pxm1Pa1qkMVE0QKH+Br1egdpsv0zNQihFKmuXneSepN7ZaenBZszGueduHJLm9su5MTiYhetHYt3ZoZOI+c6qeZFWkl4Cps2Tx5/8WR/ydubDmcEoxMfpU2w9L8w9ihoYqcRDr+3qgOLrFcuLjsp+Sl5hIAiyNSI2cr3OQLT+mYCFQeG9XIc80XmCycItQPDXBvmVKgwVKsw/y0x5KfYke7jRnq3/uKXCDFKADF7ldn+FrRFqkqPQS5/++sXDDjX9GXtLGUciKXq0qKbxuGhY/tVu2CGUl8WYNH3OnYkKyLV5Gaja8psFhZN19LGcfogEC7I/D9E48uezRVceY7q7grARUNAODTnBFbyq4EjpRD7GGZt8A9156wHgMhvZKeFItd97YHd7MIVLrK5JBu3GEt28iblhXz4sSyQRAXFAo3Tgh/SQ2agoGvfP4i/RmFK8mEUfQmOUSZdokXDS9xMvIf03gvUS7TLHsu4sTS8L3Wuz/VL1wOeKJ1tr8SMaX3uU60u133qR7NcqzAj3TfmkriH5nLFKHVQLdX51jrLXnOG10W2fCANYKXAZWtUE5ZPAgLHMwa0d99lIGdwb/mvYwb/mgVHPrVq/jHp0wV/QXBvFOd7HhnUgH/Q3yIW3vk/KQ=
      HUE_USERNAME: AgBzRhoc+24UDQkvM7Pl6ByDzKf/uFwRI9DHzQ7/kb6fBRWKonf4u0ruJTq1WZCLSEty0p4V4OnJm0YRtcQj3LjAey85HZOHeKaG1fLqlVYT6x1JqupgjxX320CCqzk1wjcbcpLxRxWvcR9hyc+lccVuVk6miiFaHgX/lNrmt2FOvPGfO5vrBSosGUsTsCGVkV7Bt6Ak60zUf/OoFUOKdj94akaPLKyC1UPP+uI/+gtAcZommB3lP35GGXEtjR6bn4YAwEMxib61GWg0KFy7rDLu3RMYHRvVsviTDhdnZ3sdj1goQoTRBtOQKfIe3lWMk3sAX1/ARXZkAiuL0bjrQt1vVxojLAuwBwnt1F4vo8Gmw0hOu4b9YFoa6Cedo6gxJLHZKdtgX8Cw66uRFjs3JW8MPTQ+xbx5GdmpFuUbgU4mWaeVTew0QjkFlne+RLAOFMA26Is/NxFD5sVGxCat91VNIC4O3Th2udhYcC/XEzbLkj2MOg5COwIiejkYwxVaf0UmjFCkFm9Tn+hT245q9+wcyYX3o1BXJVCuSu7KaTqv73Y0WGiMoNiliPg9QetjP5Ez1fXGRC4Vj/9zVDaGD7zaJuMuYtV45HGQBvn1+UVeLEyIwNdaDlDw0Pj3g5mZz5x9LamqFqA8v+VVpKDbTX24gOr0xWoIbGsJgnitTUcxluGRp2UQ8C/RgQtdD6kXLPw/db1EduL4pNshn92ySaTZyl1mBjnMh2uesJyF8sh7k+3FVP/zHTa5
      HUE_V2_BRIDGE_IP: AgBz58wuPR+a9DZ4VQ0v5HKwjbmkfNXwDbZnwONPZ6i0elWf3EfIVh9WaMZm2LeyvLOjpPquk6UGsmnS/pxm1Pa1qkMVE0QKH+Br1egdpsv0zNQihFKmuXneSepN7ZaenBZszGueduHJLm9su5MTiYhetHYt3ZoZOI+c6qeZFWkl4Cps2Tx5/8WR/ydubDmcEoxMfpU2w9L8w9ihoYqcRDr+3qgOLrFcuLjsp+Sl5hIAiyNSI2cr3OQLT+mYCFQeG9XIc80XmCycItQPDXBvmVKgwVKsw/y0x5KfYke7jRnq3/uKXCDFKADF7ldn+FrRFqkqPQS5/++sXDDjX9GXtLGUciKXq0qKbxuGhY/tVu2CGUl8WYNH3OnYkKyLV5Gaja8psFhZN19LGcfogEC7I/D9E48uezRVceY7q7grARUNAODTnBFbyq4EjpRD7GGZt8A9156wHgMhvZKeFItd97YHd7MIVLrK5JBu3GEt28iblhXz4sSyQRAXFAo3Tgh/SQ2agoGvfP4i/RmFK8mEUfQmOUSZdokXDS9xMvIf03gvUS7TLHsu4sTS8L3Wuz/VL1wOeKJ1tr8SMaX3uU60u133qR7NcqzAj3TfmkriH5nLFKHVQLdX51jrLXnOG10W2fCANYKXAZWtUE5ZPAgLHMwa0d99lIGdwb/mvYwb/mgVHPrVq/jHp0wV/QXBvFOd7HhnUgH/Q3yIW3vk/KQ=
      HUE_V2_USERNAME: AgBzRhoc+24UDQkvM7Pl6ByDzKf/uFwRI9DHzQ7/kb6fBRWKonf4u0ruJTq1WZCLSEty0p4V4OnJm0YRtcQj3LjAey85HZOHeKaG1fLqlVYT6x1JqupgjxX320CCqzk1wjcbcpLxRxWvcR9hyc+lccVuVk6miiFaHgX/lNrmt2FOvPGfO5vrBSosGUsTsCGVkV7Bt6Ak60zUf/OoFUOKdj94akaPLKyC1UPP+uI/+gtAcZommB3lP35GGXEtjR6bn4YAwEMxib61GWg0KFy7rDLu3RMYHRvVsviTDhdnZ3sdj1goQoTRBtOQKfIe3lWMk3sAX1/ARXZkAiuL0bjrQt1vVxojLAuwBwnt1F4vo8Gmw0hOu4b9YFoa6Cedo6gxJLHZKdtgX8Cw66uRFjs3JW8MPTQ+xbx5GdmpFuUbgU4mWaeVTew0QjkFlne+RLAOFMA26Is/NxFD5sVGxCat91VNIC4O3Th2udhYcC/XEzbLkj2MOg5COwIiejkYwxVaf0UmjFCkFm9Tn+hT245q9+wcyYX3o1BXJVCuSu7KaTqv73Y0WGiMoNiliPg9QetjP5Ez1fXGRC4Vj/9zVDaGD7zaJuMuYtV45HGQBvn1+UVeLEyIwNdaDlDw0Pj3g5mZz5x9LamqFqA8v+VVpKDbTX24gOr0xWoIbGsJgnitTUcxluGRp2UQ8C/RgQtdD6kXLPw/db1EduL4pNshn92ySaTZyl1mBjnMh2uesJyF8sh7k+3FVP/zHTa5
    service: null
    pprof:
      enabled: true
    autoscaling:
      enabled: false
