apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: hue
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.1.2"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: hue
    image:
      name: vibioh/hue
      tag: "202402092001" # {"$imagepolicy": "default:flux-hue-api:tag"}
    labels:
      tags.datadoghq.com/env: "production"
      tags.datadoghq.com/service: "hue"
      tags.datadoghq.com/version: "202402092001" # {"$imagepolicy": "default:flux-hue-api:tag"}
    config:
      HUE_CONFIG: /opt/config.json
      HUE_LOGGER_JSON: "true"
      HUE_TELEMETRY_RATE: "0.01"
      HUE_TELEMETRY_URL: datadog.observability:4317
      OTEL_RESOURCE_ATTRIBUTES: env=production,git.repository_url=github.com/ViBiOh/hue
    volumes:
      - name: config
        configMap:
          name: hue-config
    volumeMounts:
      - name: config
        mountPath: /opt
    env:
      - name: GOMAXPROCS
        valueFrom:
          resourceFieldRef:
            resource: limits.cpu
      - name: GOMEMLIMIT
        valueFrom:
          resourceFieldRef:
            resource: limits.memory
      - name: VERSION
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['tags.datadoghq.com/version']
      - name: OTEL_SERVICE_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['tags.datadoghq.com/service']
    secrets:
      HUE_PUBLIC_URL: AgA1nTWinPWLgMUkGLA45RFJ1WC/+hgB06Te2y9Q0ho3yaJDICF/WOQUX+EBmcvRUhHAVlKcaHOAK2BCmpOllCi8otokjC6DcUQUVXDl+nfscqVROwEJLlh15EDLSI3LGXPT+pyPRDN95uxqOigNZIfl/y4n8PLelrEmqGCOygwkYffCLduGGng1hT4W78RocUpCur2RZil0+qhEOvHMM/0RDmhvjFFdul76Am8HSWe0dK3EexM0OQ5sVz5UCVUCagrerDVvPriIYBtMkn4zCJ0dThA+3TcbbEV1x4iJD+w5s3kOrw3kyZW41N23XjhxMG5VNqQcZh5g7LEqMdeKHJeeqSt2aMStAkd7X/LRHmD8GB3UJhVZDh1qJ6g3C/ioxv/GcbVNp3fCVUeXn5umy1APZTke8Xdf79mXrotiIRUK4wDK14pydEHCUE7yvqab3YtV+GPqxcoNvZVuewexCtAtx39j3+hi1ActIAtjtKW8/wma34uC7fGdkIYoNLoBbM8cBKSUNZ8K6eUrxqcKg6H73quFWfzzA5VrXgSvkPn0U+bX3yWSLV8KpFVqZ/PEelGBGTNJbCLeGjXCcrRVRfQOXS2ctfAtyXkJKHGXobIAAjxJOrNTSuqoETYgj3g/HUoQVDMSPjoUlzK6alWn0bM07dIf/ALMRofHBJEUetJQ9gkBVnhuBRzbexPfpIU1ZuyvZIXZqyoLeAjgWfpA
      HUE_BRIDGE_IP: AgB0bLPtjkClIRX41jnrawhXQHMGlFpP9iab4jJtLeXJI8xfb84w1mYUAvKbjNu15npQxo1SdEIV/UF/0q4vVpcnZWYzfNPlXJXc9FmDP6gm4rSK/j0ILkSvsZtGm4hG4+wXX14Cg766cmtaM0TTs9P0kP/9mACPJF48blBKl/GczbfJNPKnz9Z0hhTGJZsJcxCWcfbF0OyEDgxBtZqjho997M1vybP8tjyDxk9hWUdYkGnIoiOzax3etS4MD9bKCky6Twg2tlX31TBTrQMEzGrCQDpB1SodDnm7jVTLqOLoDVPQ7kXnh9w/vWt4ffPDrDu5RnNpaghVPD6NHm2UXCic7ybfCwvM6fdHx7KCZfbAlEeOfheljH+1gRcl7H8xioyKVzJbMj1dgEa37T8XteqJz4kHaf/NHUUj3gKQAt6QGHiBuBTO9AjRUchOuCI/UVP1pS4VpLjq609pFJ9C7Ro/WstfJXFblZZNJoKjCokX9YXeivsdJFTxVz5gQPt6zlxdOZaezv+SXf3WMIXpcA5+Jb7MiQD4gC54LHeYpQdu615sh8u9uSg2oKnzBZjsi5vWDo5iNlhC+5yLzs1XE9IU0Pead6fub9rRY1F3abyEBqu94VIaODZmg5aptSNTKRhtJuJEAb41or5UyLRGhX/gCG9RSeIUBpRaII+x5RVbPx7wMLwbE6TVOeagWUMR/33O3Ivb+F5hAFLIXU0=
      HUE_USERNAME: AgBzRhoc+24UDQkvM7Pl6ByDzKf/uFwRI9DHzQ7/kb6fBRWKonf4u0ruJTq1WZCLSEty0p4V4OnJm0YRtcQj3LjAey85HZOHeKaG1fLqlVYT6x1JqupgjxX320CCqzk1wjcbcpLxRxWvcR9hyc+lccVuVk6miiFaHgX/lNrmt2FOvPGfO5vrBSosGUsTsCGVkV7Bt6Ak60zUf/OoFUOKdj94akaPLKyC1UPP+uI/+gtAcZommB3lP35GGXEtjR6bn4YAwEMxib61GWg0KFy7rDLu3RMYHRvVsviTDhdnZ3sdj1goQoTRBtOQKfIe3lWMk3sAX1/ARXZkAiuL0bjrQt1vVxojLAuwBwnt1F4vo8Gmw0hOu4b9YFoa6Cedo6gxJLHZKdtgX8Cw66uRFjs3JW8MPTQ+xbx5GdmpFuUbgU4mWaeVTew0QjkFlne+RLAOFMA26Is/NxFD5sVGxCat91VNIC4O3Th2udhYcC/XEzbLkj2MOg5COwIiejkYwxVaf0UmjFCkFm9Tn+hT245q9+wcyYX3o1BXJVCuSu7KaTqv73Y0WGiMoNiliPg9QetjP5Ez1fXGRC4Vj/9zVDaGD7zaJuMuYtV45HGQBvn1+UVeLEyIwNdaDlDw0Pj3g5mZz5x9LamqFqA8v+VVpKDbTX24gOr0xWoIbGsJgnitTUcxluGRp2UQ8C/RgQtdD6kXLPw/db1EduL4pNshn92ySaTZyl1mBjnMh2uesJyF8sh7k+3FVP/zHTa5
      HUE_V2_BRIDGE_IP: AgB0bLPtjkClIRX41jnrawhXQHMGlFpP9iab4jJtLeXJI8xfb84w1mYUAvKbjNu15npQxo1SdEIV/UF/0q4vVpcnZWYzfNPlXJXc9FmDP6gm4rSK/j0ILkSvsZtGm4hG4+wXX14Cg766cmtaM0TTs9P0kP/9mACPJF48blBKl/GczbfJNPKnz9Z0hhTGJZsJcxCWcfbF0OyEDgxBtZqjho997M1vybP8tjyDxk9hWUdYkGnIoiOzax3etS4MD9bKCky6Twg2tlX31TBTrQMEzGrCQDpB1SodDnm7jVTLqOLoDVPQ7kXnh9w/vWt4ffPDrDu5RnNpaghVPD6NHm2UXCic7ybfCwvM6fdHx7KCZfbAlEeOfheljH+1gRcl7H8xioyKVzJbMj1dgEa37T8XteqJz4kHaf/NHUUj3gKQAt6QGHiBuBTO9AjRUchOuCI/UVP1pS4VpLjq609pFJ9C7Ro/WstfJXFblZZNJoKjCokX9YXeivsdJFTxVz5gQPt6zlxdOZaezv+SXf3WMIXpcA5+Jb7MiQD4gC54LHeYpQdu615sh8u9uSg2oKnzBZjsi5vWDo5iNlhC+5yLzs1XE9IU0Pead6fub9rRY1F3abyEBqu94VIaODZmg5aptSNTKRhtJuJEAb41or5UyLRGhX/gCG9RSeIUBpRaII+x5RVbPx7wMLwbE6TVOeagWUMR/33O3Ivb+F5hAFLIXU0=
      HUE_V2_USERNAME: AgBzRhoc+24UDQkvM7Pl6ByDzKf/uFwRI9DHzQ7/kb6fBRWKonf4u0ruJTq1WZCLSEty0p4V4OnJm0YRtcQj3LjAey85HZOHeKaG1fLqlVYT6x1JqupgjxX320CCqzk1wjcbcpLxRxWvcR9hyc+lccVuVk6miiFaHgX/lNrmt2FOvPGfO5vrBSosGUsTsCGVkV7Bt6Ak60zUf/OoFUOKdj94akaPLKyC1UPP+uI/+gtAcZommB3lP35GGXEtjR6bn4YAwEMxib61GWg0KFy7rDLu3RMYHRvVsviTDhdnZ3sdj1goQoTRBtOQKfIe3lWMk3sAX1/ARXZkAiuL0bjrQt1vVxojLAuwBwnt1F4vo8Gmw0hOu4b9YFoa6Cedo6gxJLHZKdtgX8Cw66uRFjs3JW8MPTQ+xbx5GdmpFuUbgU4mWaeVTew0QjkFlne+RLAOFMA26Is/NxFD5sVGxCat91VNIC4O3Th2udhYcC/XEzbLkj2MOg5COwIiejkYwxVaf0UmjFCkFm9Tn+hT245q9+wcyYX3o1BXJVCuSu7KaTqv73Y0WGiMoNiliPg9QetjP5Ez1fXGRC4Vj/9zVDaGD7zaJuMuYtV45HGQBvn1+UVeLEyIwNdaDlDw0Pj3g5mZz5x9LamqFqA8v+VVpKDbTX24gOr0xWoIbGsJgnitTUcxluGRp2UQ8C/RgQtdD6kXLPw/db1EduL4pNshn92ySaTZyl1mBjnMh2uesJyF8sh7k+3FVP/zHTa5
    service: null
    pprof:
      enabled: true
    autoscaling:
      enabled: false
