apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hue
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.1.2"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: hue
    image:
      name: vibioh/hue
      tag: "202408090923" # {"$imagepolicy": "default:flux-hue-api:tag"}
    labels:
      tags.datadoghq.com/env: "production"
      tags.datadoghq.com/service: "hue"
      tags.datadoghq.com/version: "202408090923" # {"$imagepolicy": "default:flux-hue-api:tag"}
    config:
      HUE_CONFIG: /opt/config.json
      HUE_LOGGER_JSON: "true"
      HUE_PPROF_AGENT: http://datadog.observability:8126
      HUE_TELEMETRY_RATE: "0.01"
      HUE_TELEMETRY_URL: datadog.observability:4317
      OTEL_RESOURCE_ATTRIBUTES: env=production,git.repository_url=github.com/ViBiOh/hue
    volumes:
      - name: config
        configMap:
          name: hue-config
    volumeMounts:
      - name: config
        mountPath: /opt
    env:
      - name: GOMAXPROCS
        valueFrom:
          resourceFieldRef:
            resource: limits.cpu
      - name: GOMEMLIMIT
        valueFrom:
          resourceFieldRef:
            resource: limits.memory
      - name: VERSION
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['tags.datadoghq.com/version']
      - name: OTEL_SERVICE_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['tags.datadoghq.com/service']
    secrets:
      HUE_PUBLIC_URL: AgBRAweLFU0hO0DT+q30nPM4bIUy6O2gHPIczKnL59oww2wrwz0ZiOnHe9CZ2dCTzNWlKwD3e1Y+RTRiy3Z862JPbzVUMympINIL9Vii9YxbmtV3QCVyJ2oeQym59eTHUgPo4U8npO0QMz7xThhJSaWj96ThDG9ssFf5mjovQ63XX/JWTp/NuDhULqy3hV3Ngf1XfSZY73skUiwwMG5D8MTx4Q/BU1LS/2FpPuw4BDM5O+PhhEB8u4uqL6je/Nw7b+e+JFxukK4lXlalNYqlkla6RypwIjSwVhyENUXjQ1xFlGBvEx+wEWEs40TPvA2QQfpqtAjpJG1xEPJ/9cilG/ti4lranC1siqdGr5WfyxYcL7cxUVa//Xutt9KhkVkFz1caaot+Zv6FGiuLQ9ukwnqVG2tZm3e3aLMbK4rh0NA6ojG/xCDuMi+npSV+VKgpxzDvwoF/gNyMRmRT5UB5PnRVBa7xqWKdy1YyUsS5KgxHx6GLM0OlUTQ1z42Bc6nDfOCNIQ1DtMtVaCSQtVpKIjsIlyR3H3puE/DNgrkY/S4iDT5kH9yJhgSp8+7zWuqupzAOcGSYDumYG5xF+TxIQ2rfsd8LJVmen3QLINSRCTdmYGEkPJzp2wsS29K2k6HITHvqD/KOB3rM0Tld+94QEu30EceIKBt7WBh3syXSAwSOa7lo1Cq0OPJw2Yfvz7aexuGWdHYInj6lUg4=
      HUE_BRIDGE_IP: AgC7QZ4PWzbcvEif/x5XRp5ER9shWgsZa2j6u7LWubA1pHUe4WSP9XhsOcQWPEGnsm172SXn+UndJ+mfDTLe6qac88cNgeKCq7xXnToup4Lk2ODyo77Q9Hl4daxLFNll3+6HCNivtyQtfpas4l75xWrPyG73m07TAAf2089EfAMOTyzkFFadxCbVhuyHQC5mfMrmPgYfcii2pPFDPZif+im+61WjCQsVmuWjtTOHA9psTCk/y46LQy/muwmYV7qP5ZEqh344ZXrN0vcYWWD+zCozw4NNSgRq0wLiO8Hq0jgPzB/0H8MX/S5WL44lKZwktZkZRqFD9//B+9KrFRgkvSakmuaP9xtKIz8PbdF4YbV77X4qnPfhDtt2hbmgW5kzQwzAxEXkbIY449mLt4iLO7Xifg7+RT+C2LweQf0OKTLUhUV6ll6umZV5dgFYfyXe/EzB/3ObjtrzQx7em36gTLq2BRBsrNumqR7KloEkJANJEs1xroqwGeO2Bxb/P/plvcQq7jBkZIs2rlaomA6J7p2Dt1rZUv+na5uBN8LZzdOG3NgrgNF5VC0fTVPaAZQ7n5LcfOX0S3F+eil56gqomTE4tEdZ7fuSRaFTrEDF7b72+mSQofm8sMNZc938EpP9e1nZoYE0Dc99grDlCwS0wJvVeAR6J0FLYUxdC6YTBaTCLCQLK/XwQ/3vU1zZ7k084Nl7SVv3V4axgL0=
      HUE_USERNAME: AgBzRhoc+24UDQkvM7Pl6ByDzKf/uFwRI9DHzQ7/kb6fBRWKonf4u0ruJTq1WZCLSEty0p4V4OnJm0YRtcQj3LjAey85HZOHeKaG1fLqlVYT6x1JqupgjxX320CCqzk1wjcbcpLxRxWvcR9hyc+lccVuVk6miiFaHgX/lNrmt2FOvPGfO5vrBSosGUsTsCGVkV7Bt6Ak60zUf/OoFUOKdj94akaPLKyC1UPP+uI/+gtAcZommB3lP35GGXEtjR6bn4YAwEMxib61GWg0KFy7rDLu3RMYHRvVsviTDhdnZ3sdj1goQoTRBtOQKfIe3lWMk3sAX1/ARXZkAiuL0bjrQt1vVxojLAuwBwnt1F4vo8Gmw0hOu4b9YFoa6Cedo6gxJLHZKdtgX8Cw66uRFjs3JW8MPTQ+xbx5GdmpFuUbgU4mWaeVTew0QjkFlne+RLAOFMA26Is/NxFD5sVGxCat91VNIC4O3Th2udhYcC/XEzbLkj2MOg5COwIiejkYwxVaf0UmjFCkFm9Tn+hT245q9+wcyYX3o1BXJVCuSu7KaTqv73Y0WGiMoNiliPg9QetjP5Ez1fXGRC4Vj/9zVDaGD7zaJuMuYtV45HGQBvn1+UVeLEyIwNdaDlDw0Pj3g5mZz5x9LamqFqA8v+VVpKDbTX24gOr0xWoIbGsJgnitTUcxluGRp2UQ8C/RgQtdD6kXLPw/db1EduL4pNshn92ySaTZyl1mBjnMh2uesJyF8sh7k+3FVP/zHTa5
      HUE_V2_BRIDGE_IP: AgC7QZ4PWzbcvEif/x5XRp5ER9shWgsZa2j6u7LWubA1pHUe4WSP9XhsOcQWPEGnsm172SXn+UndJ+mfDTLe6qac88cNgeKCq7xXnToup4Lk2ODyo77Q9Hl4daxLFNll3+6HCNivtyQtfpas4l75xWrPyG73m07TAAf2089EfAMOTyzkFFadxCbVhuyHQC5mfMrmPgYfcii2pPFDPZif+im+61WjCQsVmuWjtTOHA9psTCk/y46LQy/muwmYV7qP5ZEqh344ZXrN0vcYWWD+zCozw4NNSgRq0wLiO8Hq0jgPzB/0H8MX/S5WL44lKZwktZkZRqFD9//B+9KrFRgkvSakmuaP9xtKIz8PbdF4YbV77X4qnPfhDtt2hbmgW5kzQwzAxEXkbIY449mLt4iLO7Xifg7+RT+C2LweQf0OKTLUhUV6ll6umZV5dgFYfyXe/EzB/3ObjtrzQx7em36gTLq2BRBsrNumqR7KloEkJANJEs1xroqwGeO2Bxb/P/plvcQq7jBkZIs2rlaomA6J7p2Dt1rZUv+na5uBN8LZzdOG3NgrgNF5VC0fTVPaAZQ7n5LcfOX0S3F+eil56gqomTE4tEdZ7fuSRaFTrEDF7b72+mSQofm8sMNZc938EpP9e1nZoYE0Dc99grDlCwS0wJvVeAR6J0FLYUxdC6YTBaTCLCQLK/XwQ/3vU1zZ7k084Nl7SVv3V4axgL0=
      HUE_V2_USERNAME: AgBzRhoc+24UDQkvM7Pl6ByDzKf/uFwRI9DHzQ7/kb6fBRWKonf4u0ruJTq1WZCLSEty0p4V4OnJm0YRtcQj3LjAey85HZOHeKaG1fLqlVYT6x1JqupgjxX320CCqzk1wjcbcpLxRxWvcR9hyc+lccVuVk6miiFaHgX/lNrmt2FOvPGfO5vrBSosGUsTsCGVkV7Bt6Ak60zUf/OoFUOKdj94akaPLKyC1UPP+uI/+gtAcZommB3lP35GGXEtjR6bn4YAwEMxib61GWg0KFy7rDLu3RMYHRvVsviTDhdnZ3sdj1goQoTRBtOQKfIe3lWMk3sAX1/ARXZkAiuL0bjrQt1vVxojLAuwBwnt1F4vo8Gmw0hOu4b9YFoa6Cedo6gxJLHZKdtgX8Cw66uRFjs3JW8MPTQ+xbx5GdmpFuUbgU4mWaeVTew0QjkFlne+RLAOFMA26Is/NxFD5sVGxCat91VNIC4O3Th2udhYcC/XEzbLkj2MOg5COwIiejkYwxVaf0UmjFCkFm9Tn+hT245q9+wcyYX3o1BXJVCuSu7KaTqv73Y0WGiMoNiliPg9QetjP5Ez1fXGRC4Vj/9zVDaGD7zaJuMuYtV45HGQBvn1+UVeLEyIwNdaDlDw0Pj3g5mZz5x9LamqFqA8v+VVpKDbTX24gOr0xWoIbGsJgnitTUcxluGRp2UQ8C/RgQtdD6kXLPw/db1EduL4pNshn92ySaTZyl1mBjnMh2uesJyF8sh7k+3FVP/zHTa5
    service: null
    autoscaling:
      enabled: false
