apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hue
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.92"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: hue
    image:
      name: vibioh/hue
      tag: "202309221308" # {"$imagepolicy": "default:flux-hue-api:tag"}
    config:
      GOMAXPROCS: "1"
      HUE_CONFIG: /opt/config.json
      HUE_LOGGER_JSON: "true"
      HUE_TELEMETRY_URL: otel-collector.observability:4317
      OTEL_SERVICE_NAME: hue
    volumes:
      - name: config
        configMap:
          name: hue-config
    volumeMounts:
      - name: config
        mountPath: /opt
    secrets:
      HUE_PUBLIC_URL: AgAnV14Enh3p66yStVwzPzZ3UdqEcdSMP+9+f/6O54Xr3baKSPD8InGdGlDe9BsKulhWI1HuZxeXimSLJCiWr++Z5+6Ccn3JMdv0fiyGysHYAbFSxpVs5VZYgUk5Yr4mwb23N2wSwhha3InmgBjgqt5qci5WZYGWJAw1WilCST6pHdCmTzogrbtsrHhFfT3Qnyz2L1N9NlQcgGuWbznXY/oToo9UXe/ABDE3gpipZSDFA1CuKzpuyK7uANTbsv6w6SxB2pTMF4agSpHedKcGOWNnzHMTtMNAOUU8Mj8Ial6b1ktR6Dtq8Nb7jC9dt11wNZ7htw65LKUAPpJRhKiu4fTGkH6kuQ2mnmcW02gN6N5FEAiDNP0nNN+70/XJpYR01HOD/uvHATJIHcxg5TnPvbhQNRlnvUcuu6F2p2SQf8mJ712FrfraGSSqVyNTw2sIxncaG3+Z+YoRdwplrzoxM948wGnPHmPjOO47eplYPYeLW5L13OG+RTRbtTiB4wnxn7Upoid8phXtCmLhaQRci2GhrbDdrYnTZCqajl9vm0Ap/y/CSqAP9zORd7wp/Tuwb/yoT6souuPapXaMt+mh8yXP/7eHMbpxIgQutOjShzlzxBtJQb+Civi06ZQmtInN+Bs2iptxePAU4zIU6XBb9Vm4Mn/KE2aHlOJf4QPhmVc6Y1arDFmkYiIa25v0mAmLAQIzEbiPKmJSzCQr4UR04g9xbPlong==
      HUE_BRIDGE_IP: AgCM2wGJi/MOMXiuvU71ePhdbreEg6X6CnBUSwFI41ubrO61sYDZepQ+nWjRDzx6EjQbdjiE8V07OsIULkFyhdpUB3thmDY2UmOt1/SPb8ZyJMDwFCaQhGv4Wi7tEzpYHrV1Hi4biexbwZ0nqKqekXSynUf25AZrHm4IdRwbq0EaUgsMvDCQJb8rgC7kStXtT0L+HoB6d/t6QHF4Iv6c6sXZwJtobX8hujut5GKEXTdcoMDbi9y69BDUMKJGekusrZtu/qh39uVRyb++NCW/IM9DIi8+v/pbaikIVtvDmQbN5SpV1cF6gcLngSpadl5u9q5gBmaqaNshLrv/7H9Ouq+oINsZ7uXsW9YsLFLPK6A7zTTw1J83zncFLhQwcxGgQAvHyZtzV8i+hGgY0NC0nquqMBBGL4QRixLUqG9FJiqCTZF6gJQ2FlHULoJQImZZsAuU96pNdxOqsOcrCrluaw7V7XnuAo33zkzHP61xTiHH1cQ/7gcUm3gXf1F/6afnPfQ6hquPkYF4Z+HrIaIvDWZ4X49J626hRCgLixCg7ivNKGwYJeZjIl3JRFF45RjenXQpQYH/T5kUUV/l2poJ8eOUyYx41wJ2CFBtM8HKA0Tcxj7Gf7sAV9na7HmZEcTzTC+WVeMW9aGMSdsjUPsFUW1D8JTeanTzAwCViqNTnKSu2X0mZ11JDafQ/wWkRIkbDhibZZiq9MU7i687cxI2
      HUE_USERNAME: AgBzRhoc+24UDQkvM7Pl6ByDzKf/uFwRI9DHzQ7/kb6fBRWKonf4u0ruJTq1WZCLSEty0p4V4OnJm0YRtcQj3LjAey85HZOHeKaG1fLqlVYT6x1JqupgjxX320CCqzk1wjcbcpLxRxWvcR9hyc+lccVuVk6miiFaHgX/lNrmt2FOvPGfO5vrBSosGUsTsCGVkV7Bt6Ak60zUf/OoFUOKdj94akaPLKyC1UPP+uI/+gtAcZommB3lP35GGXEtjR6bn4YAwEMxib61GWg0KFy7rDLu3RMYHRvVsviTDhdnZ3sdj1goQoTRBtOQKfIe3lWMk3sAX1/ARXZkAiuL0bjrQt1vVxojLAuwBwnt1F4vo8Gmw0hOu4b9YFoa6Cedo6gxJLHZKdtgX8Cw66uRFjs3JW8MPTQ+xbx5GdmpFuUbgU4mWaeVTew0QjkFlne+RLAOFMA26Is/NxFD5sVGxCat91VNIC4O3Th2udhYcC/XEzbLkj2MOg5COwIiejkYwxVaf0UmjFCkFm9Tn+hT245q9+wcyYX3o1BXJVCuSu7KaTqv73Y0WGiMoNiliPg9QetjP5Ez1fXGRC4Vj/9zVDaGD7zaJuMuYtV45HGQBvn1+UVeLEyIwNdaDlDw0Pj3g5mZz5x9LamqFqA8v+VVpKDbTX24gOr0xWoIbGsJgnitTUcxluGRp2UQ8C/RgQtdD6kXLPw/db1EduL4pNshn92ySaTZyl1mBjnMh2uesJyF8sh7k+3FVP/zHTa5
      HUE_V2_BRIDGE_IP: AgCM2wGJi/MOMXiuvU71ePhdbreEg6X6CnBUSwFI41ubrO61sYDZepQ+nWjRDzx6EjQbdjiE8V07OsIULkFyhdpUB3thmDY2UmOt1/SPb8ZyJMDwFCaQhGv4Wi7tEzpYHrV1Hi4biexbwZ0nqKqekXSynUf25AZrHm4IdRwbq0EaUgsMvDCQJb8rgC7kStXtT0L+HoB6d/t6QHF4Iv6c6sXZwJtobX8hujut5GKEXTdcoMDbi9y69BDUMKJGekusrZtu/qh39uVRyb++NCW/IM9DIi8+v/pbaikIVtvDmQbN5SpV1cF6gcLngSpadl5u9q5gBmaqaNshLrv/7H9Ouq+oINsZ7uXsW9YsLFLPK6A7zTTw1J83zncFLhQwcxGgQAvHyZtzV8i+hGgY0NC0nquqMBBGL4QRixLUqG9FJiqCTZF6gJQ2FlHULoJQImZZsAuU96pNdxOqsOcrCrluaw7V7XnuAo33zkzHP61xTiHH1cQ/7gcUm3gXf1F/6afnPfQ6hquPkYF4Z+HrIaIvDWZ4X49J626hRCgLixCg7ivNKGwYJeZjIl3JRFF45RjenXQpQYH/T5kUUV/l2poJ8eOUyYx41wJ2CFBtM8HKA0Tcxj7Gf7sAV9na7HmZEcTzTC+WVeMW9aGMSdsjUPsFUW1D8JTeanTzAwCViqNTnKSu2X0mZ11JDafQ/wWkRIkbDhibZZiq9MU7i687cxI2
      HUE_V2_USERNAME: AgBzRhoc+24UDQkvM7Pl6ByDzKf/uFwRI9DHzQ7/kb6fBRWKonf4u0ruJTq1WZCLSEty0p4V4OnJm0YRtcQj3LjAey85HZOHeKaG1fLqlVYT6x1JqupgjxX320CCqzk1wjcbcpLxRxWvcR9hyc+lccVuVk6miiFaHgX/lNrmt2FOvPGfO5vrBSosGUsTsCGVkV7Bt6Ak60zUf/OoFUOKdj94akaPLKyC1UPP+uI/+gtAcZommB3lP35GGXEtjR6bn4YAwEMxib61GWg0KFy7rDLu3RMYHRvVsviTDhdnZ3sdj1goQoTRBtOQKfIe3lWMk3sAX1/ARXZkAiuL0bjrQt1vVxojLAuwBwnt1F4vo8Gmw0hOu4b9YFoa6Cedo6gxJLHZKdtgX8Cw66uRFjs3JW8MPTQ+xbx5GdmpFuUbgU4mWaeVTew0QjkFlne+RLAOFMA26Is/NxFD5sVGxCat91VNIC4O3Th2udhYcC/XEzbLkj2MOg5COwIiejkYwxVaf0UmjFCkFm9Tn+hT245q9+wcyYX3o1BXJVCuSu7KaTqv73Y0WGiMoNiliPg9QetjP5Ez1fXGRC4Vj/9zVDaGD7zaJuMuYtV45HGQBvn1+UVeLEyIwNdaDlDw0Pj3g5mZz5x9LamqFqA8v+VVpKDbTX24gOr0xWoIbGsJgnitTUcxluGRp2UQ8C/RgQtdD6kXLPw/db1EduL4pNshn92ySaTZyl1mBjnMh2uesJyF8sh7k+3FVP/zHTa5
    service: null
    pprof:
      enabled: true
