#!/usr/bin/env bash

main() {
  if [[ "${#}" -lt 2 ]]; then
    echo "Usage: build [BINARY_PATH_PREFIX] [MAIN_SOURCE]"
    return 1
  fi

  local OS_ARCH=('darwin/amd64' 'linux/amd64' 'linux/arm' 'linux/arm64')

  for os_arch in "${OS_ARCH[@]}"; do
    IFS='/' read -ra context <<< "${os_arch}"

    local GOOS="${context[0]}"
    local GOARCH="${context[1]}"

    GOOS="${GOOS}" GOARCH="${GOARCH}" CGO_ENABLED=0 go build -ldflags="-s -w" -installsuffix nocgo -o "${1}_${GOOS}_${GOARCH}" "${2}"
  done
}

main "${@}"
